CREATE TABLE `ppp_order_status` (
  `sId` INT NOT NULL AUTO_INCREMENT COMMENT '主键sId',
  `orderId` VARCHAR(45) NULL COMMENT '订单Id',
  `orderStatus` VARCHAR(45) NULL COMMENT '订单状态',
  `timeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTimeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`sId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;