CREATE TABLE `ppp_advertising_pic` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '广告图片ID',
  `pic` MEDIUMBLOB NULL COMMENT '广告图片',
  `picLink` VARCHAR(45) NULL COMMENT '广告图片链接',
  `picSequence` INT NULL COMMENT '图片顺序',
  `adId` VARCHAR(45) NULL COMMENT '广告ID',
  `timeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTimeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));