CREATE TABLE `ppp_advertising_position` (
  `adPId` INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `adPName` VARCHAR(45) NULL COMMENT '广告位名称',
  `adPHeight` VARCHAR(45) NULL COMMENT '广告位高度',
  `adPWidth` VARCHAR(45) NULL COMMENT '广告位宽度',
  `adPType` VARCHAR(45) NULL COMMENT '广告位类型',
  `adPStatus` INT NULL COMMENT '广告位状态（0表示禁用，1表示启用）',
  `adPIntroduction` VARCHAR(200) NULL COMMENT '广告位简介',
  `timeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTimeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`adPId`));