CREATE TABLE `ppp_organization` (
  `orgId` INT NOT NULL AUTO_INCREMENT COMMENT '组织ID',
  `orgName` VARCHAR(45) NULL COMMENT '组织名称',
  `orgSign` VARCHAR(45) NULL COMMENT '组织签名',
  `timeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTimeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`orgId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;