ALTER TABLE `pengpengpiao`.`ppp_resource_market` 
CHANGE COLUMN `type1` `type1` VARCHAR(45) NULL DEFAULT NULL COMMENT '国有+国股 利率' ,
CHANGE COLUMN `type2` `type2` VARCHAR(45) NULL DEFAULT NULL COMMENT '大商 利率' ,
CHANGE COLUMN `type3` `type3` VARCHAR(45) NULL DEFAULT NULL COMMENT '授信城商  利率' ,
CHANGE COLUMN `type4` `type4` VARCHAR(45) NULL DEFAULT NULL COMMENT '村镇银行  利率' ,
CHANGE COLUMN `note` `note` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '备注 全部' ,
ADD COLUMN `xPerLakh1` VARCHAR(45) CHARACTER SET 'utf8' NULL COMMENT '国有+国股  每十万加' AFTER `type4`,
ADD COLUMN `xPerLakh2` VARCHAR(45) CHARACTER SET 'utf8' NULL COMMENT '大商  每十万加' AFTER `xPerLakh1`,
ADD COLUMN `xPerLakh3` VARCHAR(45) CHARACTER SET 'utf8' NULL COMMENT '授信城商  每十万加' AFTER `xPerLakh2`,
ADD COLUMN `xPerLarkh4` VARCHAR(45) CHARACTER SET 'utf8' NULL COMMENT '村镇银行  每十万加' AFTER `xPerLakh3`,
ADD COLUMN `note1` VARCHAR(300) CHARACTER SET 'utf8' NULL COMMENT '国有+国股  备注' AFTER `xPerLarkh4`,
ADD COLUMN `note2` VARCHAR(300) CHARACTER SET 'utf8' NULL COMMENT '大商  备注' AFTER `note1`,
ADD COLUMN `note3` VARCHAR(300) CHARACTER SET 'utf8' NULL COMMENT '授信城商  备注' AFTER `note2`,
ADD COLUMN `note4` VARCHAR(300) CHARACTER SET 'utf8' NULL COMMENT '村镇银行  备注' AFTER `note3`;
