CREATE TABLE `ppp_holiday` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL COMMENT '日期',
  `flag` VARCHAR(45) NULL COMMENT '是否是工作日标志,工作日为0，非工作日为1',
  `timeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTimeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));