CREATE TABLE `pengpengpiao`.`ppp_admin_operation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `operator` VARCHAR(45) NULL COMMENT '操作人员',
  `operateContent` VARCHAR(255) NULL COMMENT '操作内容',
  `ip` VARCHAR(50) NULL COMMENT '操作人的ip地址',
  `timeStamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTimeStamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;