CREATE TABLE `pengpengpiao`.`ppp_quick_bill` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '极速发票表ID',
  `billType` VARCHAR(45) NULL COMMENT '票据类型',
  `pic1` MEDIUMBLOB NULL COMMENT '票据正面图片',
  `pic2` MEDIUMBLOB NULL,
  `contactPhone` VARCHAR(45) NULL COMMENT '联系人电话',
  `timeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTimeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));
